language: perl

notifications:
    recipients:
        - shubina@reg.ru
        - a.gerasimov@reg.ru

perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"

before_install:
    - "echo 'user REGRU' > ~/.pause"
    - "cpanm -q -n RJBS/Dist-Zilla-4.300039.tar.gz"
    - "cpanm -q -n Test::CPAN::Meta"
    - "cpanm -q -n Test::Kwalitee"
    - "cpanm -q -n Test::Pod::Coverage"
    - "cpanm -q -n Test::Pod"
    - "cpanm -q -n Pod::Coverage::TrustPod"
    - "cpanm -q -n Pod::Weaver::Plugin::Encoding"
    - "dzil --version"

install:
    - "dzil authordeps --missing | xargs cpanm -q -n && dzil listdeps --missing | xargs cpanm -q -n"

script:
    - "dzil smoke --release --author"

branches:
  only:
    - master

after_success:
    - "cpanm -q -n --skip-satisfied Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls"
    - "dzil cover -report coveralls"
