language: perl

notifications:
    recipients:
        - a.gerasimov@reg.ru

perl:
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
    - "echo 'user REGRU' > ~/.pause"
    - "git config user.email 'regru@example.com'"
    - "git config user.name 'REG.RU LLC'"
    - "perlbrew --force install-cpanm"
    - "cpanm --version"
    - "dzil --version"
    - "cpanm -q -n version"
    - "cpanm -q -n Pod::Readme"
    - "cpanm -q -n Test::CPAN::Meta"
    - "cpanm -q -n Test::Kwalitee"
    - "cpanm -q -n Test::Pod::Coverage"
    - "cpanm -q -n Test::Pod"
    - "cpanm -q -n Test::EOL"
    - "cpanm -q -n Test::NoTabs"
    - "cpanm -q -n Pod::Coverage::TrustPod"
    - "cpanm -q -n Pod::Weaver::Plugin::Encoding"

install:
    - "dzil authordeps --missing | xargs cpanm -q -n && dzil listdeps --missing | xargs cpanm -q -n"

script:
    - "dzil smoke --release --author"

branches:
    only:
        - master

# after_success:
#     - "cpanm -q -n --skip-satisfied Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls"
#     - "dzil cover -report coveralls"
